package loading;

import com.mysql.jdbc.Statement;
import java.awt.Toolkit;
import javax.swing.JFrame;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class NewSignUp extends javax.swing.JFrame {
private Statement stm;
    /**
     * Creates new form NewSignUp
     */
    public NewSignUp() {
        this.setUndecorated(true);
        this.setResizable(true);
        this.setVisible(true);
        Toolkit tk = Toolkit.getDefaultToolkit();
            int xsize = (int) 1080;
            int ysize = (int) 720;
        this.setSize(xsize, ysize);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        try{
            makeConnection conn = new makeConnection();
            stm = (Statement) conn.getConnection().createStatement();
            
            this.select();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "On Start :"+e.getMessage());
        }
    }
    private void select(){
        try{
            String query = "SELECT * FROM login";
            ResultSet rs = stm.executeQuery(query);
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "On Select:"+e.getMessage());
        }
    }
    private void clear(){
    regEmail.setText("");
    regPass.setText("");
    regPass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ckVerif = new javax.swing.JCheckBox();
        regUser = new javax.swing.JTextField();
        regPass = new javax.swing.JPasswordField();
        regEmail = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton_Register = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading/minimize.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 40, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading/close.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 40, -1, -1));

        ckVerif.setBackground(new java.awt.Color(18, 12, 50));
        ckVerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckVerifActionPerformed(evt);
            }
        });
        jPanel1.add(ckVerif, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 20, -1));

        regUser.setBackground(new java.awt.Color(52, 133, 185));
        regUser.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        regUser.setForeground(new java.awt.Color(255, 255, 255));
        regUser.setText("\n");
        regUser.setToolTipText("");
        regUser.setBorder(null);
        regUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUserActionPerformed(evt);
            }
        });
        jPanel1.add(regUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 560, 30));

        regPass.setBackground(new java.awt.Color(52, 133, 185));
        regPass.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        regPass.setForeground(new java.awt.Color(255, 255, 255));
        regPass.setBorder(null);
        jPanel1.add(regPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 560, 30));

        regEmail.setBackground(new java.awt.Color(52, 133, 185));
        regEmail.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        regEmail.setForeground(new java.awt.Color(255, 255, 255));
        regEmail.setBorder(null);
        regEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEmailActionPerformed(evt);
            }
        });
        jPanel1.add(regEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 560, 30));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 560, 10));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 560, 10));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 560, 10));

        jButton_Register.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading/asign in copy.PNG"))); // NOI18N
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 633, 80, 30));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DIREKTORAT JENDRAL BEA DAN CUKAI");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 490, 70));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(189, 187, 56));
        jLabel11.setText("PROTECTION");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(52, 133, 185));
        jLabel12.setText("CUSTOM");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 12, 50));
        jLabel2.setText("<html>\n<body>\n<u>Terms And Codition</u>\n</body>\n</html>");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 150, 20));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agree");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 60, 20));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading/asign in copy.PNG"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 100, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading/asign in2.PNG"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 100, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Camera Roll\\Untitled-2 copy.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1400, 810));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DIREKTORAT JENDRAL BEA DAN CUKAI");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 490, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -9, 1390, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regEmailActionPerformed

    private void ckVerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckVerifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckVerifActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
        if (ckVerif.isSelected()) {
        try{
            if(regUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username Tidak Boleh Kosong");
        }else if (regPass.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password Tidak Boleh Kosong");
        }else if (regEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Email Tidak Boleh Kosong");
        } else {
            String query = "INSERT INTO login VALUES('"
                    +regUser.getText() + "','"
                    +regPass.getText()+"','"
                    +regEmail.getText()+"');";
            stm.executeUpdate(query);
            stm.close();
            
            JOptionPane.showMessageDialog(null, "Berhasil Ditambahkan");
            
            this.dispose();
        Login next = new Login();
        next.setVisible(true);
            
            this.clear();
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ON Save :"+ e.getMessage());
        }
        }
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Login next = new Login();
        next.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void regUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckVerif;
    private javax.swing.JButton jButton_Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField regEmail;
    private javax.swing.JPasswordField regPass;
    private javax.swing.JTextField regUser;
    // End of variables declaration//GEN-END:variables
}
