/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package loading;

import javax.swing.JFrame;
import com.mysql.jdbc.Statement;
import java.awt.GraphicsEnvironment;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ilham Irfan
 */
public class Table extends javax.swing.JFrame {

    /**
     * Creates new form Table
     */
    private Statement stm;
    private int selectTable = 0;
    
    public Table() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        try {
            makeConnection con = new makeConnection();
            stm = (Statement) con.getConnection().createStatement();
            
            DateFormat dateFormat = new SimpleDateFormat("dd");
            Date dateDay = new Date();
            String dateNow = dateFormat.format(dateDay);
            DateFormat dateFormat2 = new SimpleDateFormat("MM/yyyy");
            Date dateMonth = new Date();
            String dateNow2 = dateFormat2.format(dateMonth);
            lbBulanTahun.setText(dateNow2);
            lbTanggal.setText(dateNow);
            
            this.selectData("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "On Start : " + e.getMessage());
        }
    }
    
    private void insertTable(String Tanggal, String JenisInputan, String KodeBarang, String NamaBarang, String JumlahBarang, String JumlahMaksimum, String HargaBarang, String PajakPerBarang, String PajakTotal, String NamaPengirim, String AsalNegara, String KotaTujuan, String NegaraTujuan) {
        DefaultTableModel model = (DefaultTableModel) tbData.getModel();
        
        model.addRow(new Object[]{Tanggal, JenisInputan, KodeBarang,NamaBarang, JumlahBarang, JumlahMaksimum, HargaBarang, PajakPerBarang, PajakTotal, NamaPengirim, AsalNegara, KotaTujuan, NegaraTujuan});
    }

    private  void selectData(String search) {
        try {
            String query = "SELECT * FROM importeksport where `tanggal` Like '%" + search +"%' or `jenis` Like '%" + search +"%' or `KodeBarang` Like '%" + search +"%' or `NamaBarang` Like '%" + search +"%' or `JumlahBarang` Like '%" + search +"%' or `JumlahMaksimal` Like '%" + search +"%' or `HargaBarang` Like '%" + search +"%' or `PajakPerBarang` Like '%" + search +"%' or `PajakTotal` Like '%" + search +"%' or `NamaPengirim` Like '%" + search +"%' or `AsalNegara` Like '%" + search +"%' or `KotaTujuan` Like '%" + search +"%' or `NegaraTujuan` Like '%" + search +"%'";
            ResultSet rs = stm.executeQuery(query);
            
            while(rs.next()) {
                this.insertTable(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12), rs.getString(13));
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "On Select :" + e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbBulanTahun = new javax.swing.JLabel();
        lbTanggal = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        btnSeacrh = new javax.swing.JLabel();
        Layout = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        idData = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setUndecorated(true);
        setResizable(false);

        TopBar.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Product Sans", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bea Cukai");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading/close.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading/minimize.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Kembali ke Inputan");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        lbBulanTahun.setFont(new java.awt.Font("Product Sans", 0, 14)); // NOI18N
        lbBulanTahun.setForeground(new java.awt.Color(255, 255, 255));
        lbBulanTahun.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbBulanTahun.setText("September 2018");

        lbTanggal.setFont(new java.awt.Font("Product Sans", 0, 48)); // NOI18N
        lbTanggal.setForeground(new java.awt.Color(255, 255, 255));
        lbTanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTanggal.setText("4");

        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSearchKeyReleased(evt);
            }
        });

        btnSeacrh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loading/close.png"))); // NOI18N
        btnSeacrh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeacrhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TopBarLayout.createSequentialGroup()
                        .addComponent(btnSeacrh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 807, Short.MAX_VALUE)
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBulanTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(14, 14, 14))
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeacrh)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(TopBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lbTanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBulanTahun)
                .addGap(22, 22, 22))
        );

        Layout.setBackground(new java.awt.Color(255, 255, 255));

        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Jenis Inputan", "Kode Barang", "Nama Barang", "Jumlah Barang", "Jumlah Maksimum", "Harga Barang", "Pajak per-Barang", "Pajak Total", "Nama Pengirim", "Asal Negara", "Kota Tujuan", "Negara Tujuan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbData);

        jLabel2.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("ID");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setText("EDIT");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        idData.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        idData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        idData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDataActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("DELETE");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 74));
        jButton3.setText("PRINT");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LayoutLayout = new javax.swing.GroupLayout(Layout);
        Layout.setLayout(LayoutLayout);
        LayoutLayout.setHorizontalGroup(
            LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutLayout.createSequentialGroup()
                .addGroup(LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LayoutLayout.createSequentialGroup()
                        .addContainerGap(805, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idData, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LayoutLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        LayoutLayout.setVerticalGroup(
            LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LayoutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idData, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Layout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        ImportEKsport IE = new ImportEKsport();
        IE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnSeacrhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeacrhMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dm = (DefaultTableModel) tbData.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    
        String search = tfSearch.getText();
        selectData(search);
    }//GEN-LAST:event_btnSeacrhMouseClicked

    private void tfSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) tbData.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    
        String search = tfSearch.getText();
        selectData(search);
    }//GEN-LAST:event_tfSearchKeyReleased

    private void idDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDataActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

        editData1 s = new editData1();
        int baris = this.selectTable;

        s.setVisible(true);
        this.dispose();

        String tanggal = tbData.getValueAt(baris, 0).toString();
        s.tb1.setText(tanggal);
        String jenis = tbData.getValueAt(baris, 1).toString();
        s.tb2.setText(jenis);
        String kodebarang = tbData.getValueAt(baris, 2).toString();
        s.tb3.setText(kodebarang);
        String namabarang = tbData.getValueAt(baris, 3).toString();
        s.tb4.setText(namabarang);
        String jumlahbarang = tbData.getValueAt(baris, 4).toString();
        s.tb5.setText(jumlahbarang);
        String jumlahmaksimal = tbData.getValueAt(baris, 5).toString();
        s.tb6.setText(jumlahmaksimal);
        String hargabarang = tbData.getValueAt(baris, 6).toString();
        s.tb7.setText(hargabarang);
        String pajakperbarang = tbData.getValueAt(baris, 7).toString();
        s.tb8.setText(pajakperbarang);
        String pajaktotal = tbData.getValueAt(baris, 8).toString();
        s.tb9.setText(pajaktotal);
        String namapengirim = tbData.getValueAt(baris, 9).toString();
        s.tb10.setText(namapengirim);
        String asalnegara = tbData.getValueAt(baris, 10).toString();
        s.tb11.setText(asalnegara);
        String kotatujuan = tbData.getValueAt(baris, 11).toString();
        s.tb12.setText(kotatujuan);
        String negaratujuan = tbData.getValueAt(baris, 12).toString();
        s.tb13.setText(negaratujuan);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:struk s = new struk();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(idData.getText());
        String query = "DELETE FROM importeksport WHERE kodebarang = "+id;
        try {
            stm.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Berhasil Terhapus!");
            DefaultTableModel dm = (DefaultTableModel) tbData.getModel();
            int rowCount = dm.getRowCount();
            //Remove rows one by one from the end of the table
            for (int i = rowCount - 1; i >= 0; i--) {
                dm.removeRow(i);
            }
            selectData("");
        } catch (SQLException ex) {
            Logger.getLogger(TablePajak.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        // TODO add your handling code here:
        int baris = tbData.rowAtPoint(evt.getPoint());
        String id = tbData.getValueAt(baris, 2).toString();
        this.selectTable = baris;
        idData.setText(id);
    }//GEN-LAST:event_tbDataMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        struk s = new struk();
        int baris = this.selectTable;

        s.setVisible(true);
        this.dispose();

        String tanggal = tbData.getValueAt(baris, 0).toString();

        String jenis = tbData.getValueAt(baris, 1).toString();
     
        String kodebarang = tbData.getValueAt(baris, 2).toString();
  
        String namabarang = tbData.getValueAt(baris, 3).toString();
      
        String jumlahbarang = tbData.getValueAt(baris, 4).toString();
      
        String jumlahmaksimal = tbData.getValueAt(baris, 5).toString();

        String hargabarang = tbData.getValueAt(baris, 6).toString();
       
        String pajakperbarang = tbData.getValueAt(baris, 7).toString();
        
        String pajaktotal = tbData.getValueAt(baris, 8).toString();
        
        String namapengirim = tbData.getValueAt(baris, 9).toString();
        
        String asalnegara = tbData.getValueAt(baris, 10).toString();
       
        String kotatujuan = tbData.getValueAt(baris, 11).toString();
       
        String negaratujuan = tbData.getValueAt(baris, 12).toString();
       
       
            s.tanggal.setText(tanggal);
            s.jenis.setText(jenis);
            s.kodebarang.setText(kodebarang);
            s.namabarang.setText(namabarang);
            s.jumlahbarang.setText(jumlahbarang);
            s.jumlahmaksimal.setText(jumlahmaksimal);
            s.hargabarang.setText(hargabarang);
            s.pajakperbarang.setText(pajakperbarang);
            s.pajaktotal.setText(pajaktotal);
            s.pengirim.setText(namapengirim);
            s.asalnegara.setText(asalnegara);
            s.kotatujuan.setText(kotatujuan);
            s.negaratujuan.setText(negaratujuan);
       
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Table().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Layout;
    private javax.swing.JPanel TopBar;
    private javax.swing.JLabel btnSeacrh;
    private javax.swing.JTextField idData;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBulanTahun;
    private javax.swing.JLabel lbTanggal;
    private javax.swing.JTable tbData;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
